"use client";
import { useEffect, useRef, useState } from "react";
import Link from "next/link";
import { useAuth } from "@/components/AuthProvider";
import AuthGate from "@/components/AuthGate";
import PageShell from "@/components/PageShell";
import CardForm from "@/components/CardForm";
import CollectionPdfExport from "@/components/CollectionPdfExport";
import { emptyCard } from "@/lib/defaults";
import { findDuplicate } from "@/lib/storage";
import { loadWants,saveWant,deleteWant,acquireWant,type WantedCard } from "@/lib/organize";
import { ebayActiveUrl } from "@/lib/matching";
import type { CardRecord } from "@/lib/types";
export default function WantListPage() {
  const {user}=useAuth();const userRef=useRef(user?.id);userRef.current=user?.id;
  const [wants,setWants]=useState<WantedCard[]>([]);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [status,setStatus]=useState("");
  const [draft,setDraft]=useState<CardRecord>(emptyCard);const [editing,setEditing]=useState<string|undefined>();const [showForm,setShowForm]=useState(false);const [search,setSearch]=useState("");const [pending,setPending]=useState<{want:WantedCard;match:CardRecord}|null>(null);const [acquiredId,setAcquiredId]=useState("");
  async function refresh(){const uid=userRef.current;const next=await loadWants();if(uid===userRef.current)setWants(next);}
  useEffect(()=>{let active=true;setLoading(true);setWants([]);setStatus("");setPending(null);if(user)loadWants().then(next=>{if(active)setWants(next);}).catch(e=>{if(active)setStatus(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[user?.id]);
  async function action(run:()=>Promise<unknown>){if(busy)return;setBusy(true);setStatus("");setAcquiredId("");try{await run();await refresh();}catch(e:any){setStatus(e.message||"Could not update your want list.");}finally{setBusy(false);}}
  async function move(want:WantedCard){await action(async()=>{const match=await findDuplicate(want.card);if(match){setPending({want,match});return;}setAcquiredId(await acquireWant(want.id));setStatus("Moved to your collection.");});}
  const filtered=wants.filter(w=>[w.card.player,w.card.year,w.card.brand,w.card.set,w.card.parallel,w.card.cardNumber].join(" ").toLowerCase().includes(search.toLowerCase()));
  return <AuthGate><PageShell title="Your want list">
    <p className="vaultWelcomeCopy">Keep track of missing cards and variations. Wanted cards do not count toward your owned collection or its value.</p>
    <div className="buttonRow organizeNav"><Link className="btn ghost" href="/collection">All cards</Link><Link className="btn ghost" href="/binders">Binders</Link><button className="btn primary" disabled={busy||loading} onClick={()=>{setDraft(emptyCard());setEditing(undefined);setShowForm(true);}}>Add wanted card</button><CollectionPdfExport cards={wants.map(w=>w.card)} filtered={filtered.map(w=>w.card)} disabled={busy||loading} kind="wanted"/></div>
    {status?<p className="workflowNotice" role="status">{status}{acquiredId?<><br/><Link className="vaultTextLink" href={`/card/${acquiredId}`}>View the card in your collection</Link></>:null}</p>:null}
    {pending?<section className="panel"><h2>You already own a matching card.</h2><p>{pending.match.player} · {pending.match.year} · {pending.match.brand} · #{pending.match.cardNumber}</p><p className="helperText">Add the wanted quantity to that card, or create a separate collection entry.</p><div className="buttonRow"><button className="btn primary" disabled={busy} onClick={()=>void action(async()=>{setAcquiredId(await acquireWant(pending.want.id,pending.match.id));setPending(null);setStatus("Quantity added to your collection.");})}>Add to existing quantity</button><button className="btn ghost" disabled={busy} onClick={()=>void action(async()=>{setAcquiredId(await acquireWant(pending.want.id));setPending(null);setStatus("Moved to your collection.");})}>Save as separate card</button><button className="btn ghost" disabled={busy} onClick={()=>setPending(null)}>Cancel move</button></div></section>:null}
    {showForm?<section className="panel" id="wanted-editor"><h2>{editing?"Edit wanted card":"Add a wanted card"}</h2><form onSubmit={e=>{e.preventDefault();void action(async()=>{await saveWant(draft,editing);setShowForm(false);setDraft(emptyCard());setEditing(undefined);setStatus("Wanted card saved.");});}}><fieldset disabled={busy} style={{border:0,padding:0,margin:0}}><CardForm value={draft} onChange={setDraft} showImageFields={false} wanted/><div className="buttonRow" style={{marginTop:20}}><button className="btn primary">Save wanted card</button><button className="btn ghost" type="button" onClick={()=>setShowForm(false)}>Cancel</button></div></fieldset></form></section>:null}
    <section className="panel"><label className="label" htmlFor="want-search">Search wanted cards</label><input type="search" className="input" id="want-search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Player, year, brand or variation"/><p className="helperText">{filtered.length} wanted entries</p></section>
    {loading?<p role="status">Loading your want list…</p>:!filtered.length?<section className="vaultEmptyState"><h2>{wants.length?"No matches.":"What are you looking for next?"}</h2><p>{wants.length?"Try another search.":"Add a missing card or a variation you want to find."}</p></section>:<div className="wantListRows">{filtered.map(want=><section className="panel" key={want.id}><span className="vaultEyebrow">Wanted · Qty {want.card.quantity}</span><h2>{want.card.player}</h2><p>{[want.card.year,want.card.brand,want.card.set,want.card.subset,want.card.cardNumber&&`#${want.card.cardNumber}`,want.card.parallel,want.card.serialNumber,[want.card.gradingCompany,want.card.grade].filter(Boolean).join(" "),want.card.rookie&&"Rookie",want.card.autograph&&"Autograph",want.card.relicPatch&&"Relic/Patch"].filter(Boolean).join(" · ")}</p>{want.card.notes?<p className="helperText">{want.card.notes}</p>:null}<div className="buttonRow"><button className="btn primary" disabled={busy} onClick={()=>void move(want)}>Move to collection</button><button className="btn ghost" disabled={busy} onClick={()=>{setPending(null);setDraft({...want.card});setEditing(want.id);setShowForm(true);requestAnimationFrame(()=>document.getElementById("wanted-editor")?.scrollIntoView({behavior:"smooth"}));}}>Edit wanted card</button><a className="btn ghost" href={ebayActiveUrl(want.card)} target="_blank" rel="noopener noreferrer">Search eBay</a><button className="btn ghost" disabled={busy} onClick={()=>{if(window.confirm("Remove this card from your want list?"))void action(()=>deleteWant(want.id));}}>Remove wanted card</button></div></section>)}</div>}
  </PageShell></AuthGate>;
}
