import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { PGlite } from '@electric-sql/pglite';

const db = new PGlite();
const a = '11111111-1111-4111-8111-111111111111';
const b = '22222222-2222-4222-8222-222222222222';
await db.exec(`
  create role anon; create role authenticated; create role service_role bypassrls;
  create schema auth; create schema storage;
  create table auth.users (id uuid primary key, email text, raw_user_meta_data jsonb default '{}');
  create function auth.uid() returns uuid language sql stable as $$
    select nullif(current_setting('request.jwt.claim.sub', true), '')::uuid
  $$;
  create table storage.buckets (id text primary key, name text, public boolean);
  create table storage.objects (id uuid default gen_random_uuid(), bucket_id text, name text);
  alter table storage.objects enable row level security;
  create function storage.foldername(text) returns text[] language sql as $$ select string_to_array($1, '/') $$;
  grant usage on schema public, auth, storage to anon, authenticated, service_role;
  grant execute on function auth.uid() to anon, authenticated, service_role;
  alter default privileges in schema public grant all on tables to anon, authenticated, service_role;
`);
const schema = (await readFile(new URL('../supabase/schema.sql', import.meta.url), 'utf8'))
  .replace('create extension if not exists pgcrypto;', '');
await db.exec(schema);
await db.exec(`insert into auth.users values ('${a}', 'alice@example.test', '{"username":"alice","role":"admin"}'),
  ('${b}', 'bob@example.test', '{"username":"bob"}');`);
const rows = await db.query('select username, role from public.profiles order by username');
assert.deepEqual(rows.rows, [{username:'alice',role:'user'},{username:'bob',role:'user'}]);
console.log('PASS signup creates profiles and ignores user-provided admin role');

await db.exec(`set role authenticated; select set_config('request.jwt.claim.sub','${a}',false);`);
assert.equal((await db.query('select count(*)::int as n from public.profiles')).rows[0].n, 1);
assert.equal((await db.query('select email from public.profiles')).rows[0].email, 'alice@example.test');
console.log('PASS authenticated users can read only their own profile');
await assert.rejects(db.exec(`update public.profiles set role='admin' where id='${a}'`), /permission denied/);
await assert.rejects(db.exec(`insert into public.profiles(id,username,email,role) values('${a}','x','x@example.test','admin')`), /permission denied/);
await assert.rejects(db.exec(`update public.profiles set email='stolen@example.test' where id='${a}'`), /permission denied/);
console.log('PASS direct role changes, profile insertion, and email spoofing are denied');
await db.exec(`update public.profiles set username='alice_new' where id='${a}'`);
assert.equal((await db.query('select username from public.profiles')).rows[0].username, 'alice_new');
await db.exec(`update public.profiles set username='stolen' where id='${b}'`);
console.log('PASS own username updates work while other users are protected');
await assert.rejects(db.query('select public.admin_dashboard()'), /Not authorized/);
console.log('PASS regular users cannot access the privileged dashboard');
await db.exec('reset role; set role anon;');
await assert.rejects(db.query('select email from public.profiles'), /permission denied/);
await assert.rejects(db.query('select public.admin_dashboard()'), /permission denied/);
await assert.rejects(db.query('select private.create_user_profile()'), /permission denied/);
console.log('PASS anonymous clients cannot read emails or invoke privileged helpers');
await db.exec(`reset role; set role service_role; update public.profiles set role='admin' where id='${a}'; reset role;`);
const migration = await readFile(new URL('../supabase/migrations/20261002012728_harden_profiles.sql', import.meta.url), 'utf8');
await db.exec(`alter table auth.users disable trigger shadowfox_create_user_profile;
  insert into auth.users values ('33333333-3333-4333-8333-333333333333','legacy@example.test','{}');
  alter table auth.users enable trigger shadowfox_create_user_profile;`);
await db.exec(migration);
assert.equal((await db.query("select role from public.profiles where email='legacy@example.test'")).rows[0].role, 'user');
console.log('PASS missing profiles for existing accounts are backfilled');
assert.equal((await db.query(`select role from public.profiles where id='${a}'`)).rows[0].role, 'admin');
console.log('PASS trusted server can assign roles and reapplying hardening preserves them');
await db.exec(`update auth.users set email='alice.updated@example.test' where id='${a}'`);
assert.equal((await db.query(`select email,role from public.profiles where id='${a}'`)).rows[0].email, 'alice.updated@example.test');
assert.equal((await db.query(`select role from public.profiles where id='${a}'`)).rows[0].role, 'admin');
console.log('PASS confirmed auth email sync preserves the role');
await db.exec(`set role authenticated; select set_config('request.jwt.claim.sub','${a}',false);`);
assert.equal((await db.query('select public.admin_dashboard() as dashboard')).rows[0].dashboard.totalUsers, 3);
console.log('PASS legitimate admin dashboard access works');
await db.exec('reset role;');

const cardId = '44444444-4444-4444-8444-444444444444';
const image = `https://project.supabase.co/storage/v1/object/public/card-images/${a}/front/test.jpg`;
await db.exec(`insert into public.cards(id,user_id,player,front_image_url) values('${cardId}','${a}','Test Player','${image}');`);
await db.exec(`set role authenticated; select set_config('request.jwt.claim.sub','${a}',false);`);
await Promise.all(Array.from({ length: 12 }, () => db.query(`select public.increment_card_quantity('${cardId}',1)`)));
assert.equal((await db.query(`select quantity from public.cards where id='${cardId}'`)).rows[0].quantity, 13);
await assert.rejects(db.query(`select public.increment_card_quantity('${cardId}',0)`), /positive/);
await db.exec(`select set_config('request.jwt.claim.sub','${b}',false);`);
await assert.rejects(db.query(`select public.increment_card_quantity('${cardId}',1)`), /Card not found/);
console.log('PASS atomic quantity additions, validation, and owner isolation');
await db.exec(`select set_config('request.jwt.claim.sub','${a}',false);`);
await db.exec(`update public.cards set front_image_url='' where id='${cardId}'`);
assert.equal((await db.query('select image_url from public.card_image_cleanup')).rows[0].image_url, image);
await assert.rejects(db.exec(`insert into public.card_image_cleanup(user_id,image_url) values('${a}','fake')`), /permission denied/);
await db.exec(`select set_config('request.jwt.claim.sub','${b}',false);`);
assert.equal((await db.query('select count(*)::int as n from public.card_image_cleanup')).rows[0].n, 0);
console.log('PASS replacement queues cleanup and clients cannot enqueue or read other owners’ jobs');
await db.exec(`reset role; update public.cards set front_image_url='${image}' where id='${cardId}';`);
await db.exec('delete from public.card_image_cleanup;');
await db.exec(`begin; delete from public.cards where id='${cardId}'; rollback;`);
assert.equal((await db.query('select count(*)::int as n from public.card_image_cleanup')).rows[0].n, 0);
await db.exec(`delete from public.cards where id='${cardId}'`);
assert.equal((await db.query('select count(*)::int as n from public.card_image_cleanup')).rows[0].n, 1);
console.log('PASS deletion queues cleanup transactionally and rollbacks preserve images');
await db.exec('reset role');
await db.exec(await readFile(new URL('../supabase/migrations/20261002201538_binders_and_want_list.sql', import.meta.url), 'utf8'));
const binderA = '55555555-5555-4555-8555-555555555555';
const binderB = '66666666-6666-4666-8666-666666666666';
const ownedA = '77777777-7777-4777-8777-777777777777';
const ownedB = '88888888-8888-4888-8888-888888888888';
await db.exec(`insert into public.cards(id,user_id,player) values('${ownedA}','${a}','Owned A'),('${ownedB}','${b}','Owned B');
insert into public.binders(id,user_id,name) values('${binderA}','${a}','A binder'),('${binderB}','${b}','B binder');`);
await db.exec(`set role authenticated; select set_config('request.jwt.claim.sub','${a}',false);`);
assert.equal((await db.query('select count(*)::int n from public.binders')).rows[0].n, 1);
await assert.rejects(db.exec(`insert into public.binder_cards(binder_id,card_id,user_id) values('${binderA}','${ownedB}','${a}')`), /foreign key/);
await assert.rejects(db.exec(`insert into public.binder_cards(binder_id,card_id,user_id) values('${binderB}','${ownedA}','${a}')`), /foreign key/);
await assert.rejects(db.exec(`insert into public.binders(user_id,name) values('${b}','Spoofed')`), /row-level/);
await db.exec(`insert into public.binder_cards(binder_id,card_id) values('${binderA}','${ownedA}')`);
await db.exec(`delete from public.binders where id='${binderA}'`);
assert.equal((await db.query(`select count(*)::int n from public.cards where id='${ownedA}'`)).rows[0].n, 1);
assert.equal((await db.query('select count(*)::int n from public.binder_cards')).rows[0].n, 0);
console.log('PASS binders isolate owners and deleting folders preserves owned cards');
const wanted = {sport:'Hockey', player:'Wanted test', quantity:2, year:'2021-22',brand:'Upper Deck',set:'MVP'};
const w = await db.query(`insert into public.want_list(card_data) values($1) returning id`, [JSON.stringify(wanted)]);
const wid = w.rows[0].id;
await assert.rejects(db.query(`insert into public.want_list(card_data) values($1)`, [JSON.stringify({player:'Missing keys'})]), /check constraint/);
await db.exec(`select set_config('request.jwt.claim.sub','${b}',false);`);
assert.equal((await db.query('select count(*)::int n from public.want_list')).rows[0].n, 0);
await assert.rejects(db.query('select public.acquire_wanted_card($1)',[wid]), /unavailable/);
await db.exec(`select set_config('request.jwt.claim.sub','${a}',false);`);
await assert.rejects(db.query('select public.acquire_wanted_card($1,$2)',[wid,ownedB]), /unavailable/);
assert.equal((await db.query('select count(*)::int n from public.want_list')).rows[0].n, 1);
const acquired = await db.query('select public.acquire_wanted_card($1) id',[wid]);
assert.equal((await db.query('select quantity,estimated_value_cad from public.cards where id=$1',[acquired.rows[0].id])).rows[0].quantity,2);
assert.equal((await db.query('select count(*)::int n from public.want_list')).rows[0].n, 0);
await assert.rejects(db.query('select public.acquire_wanted_card($1)',[wid]), /unavailable/);
const w2 = await db.query(`insert into public.want_list(card_data) values($1) returning id`,[JSON.stringify(wanted)]);
await db.query('select public.acquire_wanted_card($1,$2)',[w2.rows[0].id,acquired.rows[0].id]);
assert.equal((await db.query('select quantity from public.cards where id=$1',[acquired.rows[0].id])).rows[0].quantity,4);
await db.exec('reset role; set role anon;');
await assert.rejects(db.query('select * from public.want_list'), /permission denied/);
await assert.rejects(db.query('select public.acquire_wanted_card($1)',[wid]), /permission denied/);
console.log('PASS wanted cards stay private and acquisition is atomic, repeat-safe, and can merge quantity');
await db.exec('reset role');
await db.exec(await readFile(new URL('../supabase/migrations/20261002204031_purchase_sale_ledger.sql', import.meta.url), 'utf8'));
await db.exec(`set role authenticated; select set_config('request.jwt.claim.sub','${a}',false);`);
const transaction = await db.query(`insert into public.card_transactions(card_id,card_label,kind,occurred_on,quantity,amount_cents,fees_cents,cost_cents) values($1,'Saved card identity','sale','2026-10-02',2,2500,525,1000) returning id`,[ownedA]);
const transactionId=transaction.rows[0].id;
assert.equal((await db.query(`select quantity from public.cards where id='${ownedA}'`)).rows[0].quantity,1);
await assert.rejects(db.query(`insert into public.card_transactions(card_id,card_label,kind,occurred_on,quantity,amount_cents) values($1,'Foreign card','sale','2026-10-02',1,100)`,[ownedB]),/foreign key/);
await assert.rejects(db.exec(`insert into public.card_transactions(user_id,card_label,kind,occurred_on,quantity,amount_cents) values('${b}','Spoof','sale','2026-10-02',1,100)`),/row-level/);
await assert.rejects(db.query('update public.card_transactions set amount_cents=-1 where id=$1',[transactionId]),/check constraint/);
await assert.rejects(db.query('update public.card_transactions set quantity=0 where id=$1',[transactionId]),/check constraint/);
await assert.rejects(db.query(`update public.card_transactions set kind='purchase' where id=$1`,[transactionId]),/check constraint/);
await assert.rejects(db.query(`update public.card_transactions set user_id=$1 where id=$2`,[b,transactionId]),/permission denied/);
await db.exec(`select set_config('request.jwt.claim.sub','${b}',false);`);
assert.equal((await db.query('select count(*)::int n from public.card_transactions')).rows[0].n,0);
assert.equal((await db.query('update public.card_transactions set amount_cents=0 where id=$1 returning id',[transactionId])).rows.length,0);
assert.equal((await db.query('delete from public.card_transactions where id=$1 returning id',[transactionId])).rows.length,0);
await db.exec(`select set_config('request.jwt.claim.sub','${a}',false); delete from public.cards where id='${ownedA}';`);
const preserved=(await db.query('select card_id,card_label,user_id from public.card_transactions where id=$1',[transactionId])).rows[0];
assert.equal(preserved.card_id,null);assert.equal(preserved.card_label,'Saved card identity');assert.equal(preserved.user_id,a);
await db.exec('reset role; set role anon;');
await assert.rejects(db.query('select * from public.card_transactions'),/permission denied/);
console.log('PASS financial records preserve history, leave inventory unchanged, enforce valid money, and isolate owners');
await db.exec('reset role;');
await db.exec(await readFile(new URL('../supabase/migrations/20261002230530_set_completion_checklists.sql',import.meta.url),'utf8'));
await db.exec(`set role authenticated; select set_config('request.jwt.claim.sub','${a}',false);`);
const checklist=(await db.query(`insert into public.set_checklists(user_id,title,sport,year,brand,set_name,entries) values($1,'Test set','Hockey','2025-26','Upper Deck','Series 1','[{"number":"1","player":"","team":""}]') returning id`,[a])).rows[0].id;
await assert.rejects(db.query(`update public.set_checklists set user_id=$1 where id=$2`,[b,checklist]),/row-level security/);
await assert.rejects(db.query(`insert into public.set_checklists(user_id,title,sport,year,brand,set_name,entries) values($1,'Foreign','Hockey','2025-26','Upper Deck','Series 1','[{"number":"1","player":"","team":""}]')`,[b]),/row-level security|check constraint/);
await db.exec(`select set_config('request.jwt.claim.sub','${b}',false);`);
assert.equal((await db.query('select count(*)::int n from public.set_checklists')).rows[0].n,0);
assert.equal((await db.query("update public.set_checklists set title='Changed' where id=$1 returning id",[checklist])).rows.length,0);
assert.equal((await db.query('delete from public.set_checklists where id=$1 returning id',[checklist])).rows.length,0);
await db.exec(`select set_config('request.jwt.claim.sub','${a}',false);`);
await db.query('delete from public.set_checklists where id=$1',[checklist]);
await db.exec('reset role; set role anon;');await assert.rejects(db.query('select * from public.set_checklists'),/permission denied/);
console.log('PASS saved set checklists isolate owners, refuse reassignment and deny anonymous reads');
await db.exec('reset role;');await db.exec(await readFile(new URL('../supabase/migrations/20261002234604_published_checklist_sources.sql',import.meta.url),'utf8'));
assert.equal((await db.query("select count(*)::int n from information_schema.columns where table_name='set_checklists' and column_name like 'source_%'")).rows[0].n,3);
await db.exec(await readFile(new URL('../supabase/migrations/20261004013643_tcdb_checklist_source.sql', import.meta.url), 'utf8'));
await db.exec(`set role authenticated;select set_config('request.jwt.claim.sub','${a}',false);`);
const communityList = crypto.randomUUID();
await db.query("insert into public.set_checklists(id,user_id,title,sport,year,brand,set_name,entries,source_url) values($1,$2,'Community source','Hockey','2026-27','Upper Deck','Tim Hortons','[{\"number\":\"14\",\"player\":\"Nick Suzuki\",\"team\":\"\"}]','https://www.tcdb.com/Checklist.cfm/sid/688992/2026-27-Upper-Deck-Tim-Hortons')", [communityList,a]);
await assert.rejects(db.query("update public.set_checklists set source_url='https://www.tcdb.com.evil.example/Checklist.cfm/sid/1/x' where id=$1", [communityList]), /check constraint/);
await db.query('delete from public.set_checklists where id=$1', [communityList]);
await db.exec('reset role;');
console.log('PASS community checklist source is allowed without widening ownership or URL hosts');
await db.exec(`reset role;create table if not exists public.site_content(key text primary key,value jsonb not null,updated_at timestamptz not null default now());grant all on public.site_content to service_role;`);
await db.exec(await readFile(new URL('../supabase/migrations/20261003011723_admin_activity_history.sql',import.meta.url),'utf8'));
await db.exec(await readFile(new URL('../supabase/migrations/20261003012508_admin_activity_service_access.sql',import.meta.url),'utf8'));
await db.exec(`set role service_role;select set_config('request.headers','{}',false);`);
const auditedCard=(await db.query(`insert into public.cards(user_id,player) values($1,'Before edit') returning id`,[b])).rows[0].id;
await db.exec(`select set_config('request.headers','{"x-shadowfox-admin":"${a}"}',false);`);
await db.query(`update public.cards set player='After edit',notes='private note',front_image_url='private image' where id=$1`,[auditedCard]);
const editLog=(await db.query(`select * from public.admin_activity where subject_id=$1`,[auditedCard])).rows[0];assert.equal(editLog.actor_id,a);assert.equal(editLog.action,'card.updated');assert.deepEqual(editLog.details.fields,['notes','player']);assert.ok(!JSON.stringify(editLog).includes('private note')&&!JSON.stringify(editLog).includes('private image'));
await db.query(`insert into public.site_content(key,value) values('shop','{"heroTitle":"New heading"}')`);assert.equal((await db.query(`select count(*)::int n from public.admin_activity where action='content.updated'`)).rows[0].n,1);
await db.query(`update public.profiles set role='admin' where id=$1`,[b]);assert.equal((await db.query(`select count(*)::int n from public.admin_activity where action='user.role_changed'`)).rows[0].n,1);
await db.exec(`select set_config('request.headers','{}',false);`);await db.query(`update public.profiles set role='user' where id=$1`,[b]);
await db.exec(`select set_config('request.headers','{"x-shadowfox-admin":"${b}"}',false);`);
await assert.rejects(db.query(`update public.cards set player='Must roll back' where id=$1`,[auditedCard]),/verified admin actor/);assert.equal((await db.query(`select player from public.cards where id=$1`,[auditedCard])).rows[0].player,'After edit');
await db.exec(`reset role;set role authenticated;select set_config('request.jwt.claim.sub','${b}',false);select set_config('request.headers','{"x-shadowfox-admin":"${a}"}',false);`);
await db.query(`update public.cards set player='Normal owner edit' where id=$1`,[auditedCard]);await assert.rejects(db.query('select * from public.admin_activity'),/permission denied/);await assert.rejects(db.query(`insert into public.admin_activity(actor_label,action,subject_type,subject_id,summary) values('forged','card.deleted','card','fake','fake')`),/permission denied/);
await db.exec(`reset role;set role anon;`);await assert.rejects(db.query('select * from public.admin_activity'),/permission denied/);
await db.exec(`reset role;revoke insert on public.admin_activity from service_role;set role service_role;select set_config('request.headers','{"x-shadowfox-admin":"${a}"}',false);`);
await assert.rejects(db.query(`update public.cards set player='Unaudited change' where id=$1`,[auditedCard]),/permission denied/);assert.equal((await db.query('select player from public.cards where id=$1',[auditedCard])).rows[0].player,'Normal owner edit');
await db.exec(`reset role;grant insert on public.admin_activity to service_role;set role service_role;`);await db.query('delete from public.cards where id=$1',[auditedCard]);assert.equal((await db.query(`select count(*)::int n from public.admin_activity where action='card.deleted'`)).rows[0].n,1);assert.equal((await db.query(`select count(*)::int n from public.admin_activity where action='card.updated'`)).rows[0].n,1);
await db.exec('reset role;');
console.log('PASS admin history is private, rejects forged actors, omits private payloads and rolls back unaudited changes');

await db.exec(await readFile(new URL('../supabase/migrations/20261003032958_card_price_evidence.sql',import.meta.url),'utf8'));
await db.exec(`set role authenticated;select set_config('request.jwt.claim.sub','${a}',false);`);
const priceCard=(await db.query(`insert into public.cards(user_id,player,estimated_value_cad,price_evidence) values($1,'Price test',30,$2::jsonb) returning id`,[a,JSON.stringify({checkedAt:'2026-10-03T00:00:00Z',method:'reviewed-sales',sourceLabel:'Reviewed',sourceUrl:'https://130point.com/sales/',estimateCad:30,sales:[{amount:30,currency:'CAD',context:'sold'}]})])).rows[0].id;
await db.exec(`select set_config('request.jwt.claim.sub','${b}',false);`);assert.equal((await db.query('update public.cards set estimated_value_cad=40 where id=$1 returning id',[priceCard])).rows.length,0);
await db.exec(`select set_config('request.jwt.claim.sub','${a}',false);`);await db.query('update public.cards set estimated_value_cad=40 where id=$1',[priceCard]);assert.equal((await db.query('select price_evidence from public.cards where id=$1',[priceCard])).rows[0].price_evidence,null);
await assert.rejects(db.query(`update public.cards set price_evidence=$2::jsonb where id=$1`,[priceCard,JSON.stringify({checkedAt:'2026-10-03',method:'manual',sourceLabel:'Manual',sourceUrl:'',estimateCad:30,sales:[]})]),/check constraint/);
await db.exec('reset role;');console.log('PASS price evidence obeys ownership and clears stale support when only the value changes');

await db.exec(await readFile(new URL('../supabase/migrations/20261003034329_bulk_collection_editing.sql',import.meta.url),'utf8'));
const bulkOne='a1000000-0000-4000-8000-000000000001',bulkTwo='a1000000-0000-4000-8000-000000000002',bulkForeign='a1000000-0000-4000-8000-000000000003',bulkBinder='a1000000-0000-4000-8000-000000000004',foreignBinder='a1000000-0000-4000-8000-000000000005';
await db.exec(`insert into public.cards(id,user_id,player,quantity,estimated_value_cad,parallel) values('${bulkOne}','${a}','Bulk A',9,30,'Silver'),('${bulkTwo}','${a}','Bulk B',2,15,'Gold'),('${bulkForeign}','${b}','Foreign',1,0,'');insert into public.binders(id,user_id,name) values('${bulkBinder}','${a}','Bulk test'),('${foreignBinder}','${b}','Foreign binder');`);
await db.exec(`set role authenticated;select set_config('request.jwt.claim.sub','${a}',false);`);
await assert.rejects(db.query(`select public.bulk_update_cards(array['${bulkOne}','${bulkForeign}']::uuid[],'{"brand":"Incorrect"}','${bulkBinder}')`),/missing or unavailable/);
assert.equal((await db.query(`select brand from public.cards where id='${bulkOne}'`)).rows[0].brand,'');
assert.equal((await db.query(`select count(*)::int n from public.binder_cards where binder_id='${bulkBinder}'`)).rows[0].n,0);
await assert.rejects(db.query(`select public.bulk_update_cards(array['${bulkOne}']::uuid[],'{"team":"Incorrect"}','${foreignBinder}')`),/binder is unavailable/);
await assert.rejects(db.query(`select public.bulk_update_cards(array['${bulkOne}']::uuid[],'{"user_id":"${b}"}',null)`),/Unsupported/);
await assert.rejects(db.query(`select public.bulk_update_cards(array['${bulkOne}']::uuid[],'{"estimated_value_cad":"999"}',null)`),/Unsupported/);
await assert.rejects(db.query(`select public.bulk_update_cards(array['${bulkOne}','${bulkOne}']::uuid[],'{}','${bulkBinder}')`),/duplicates/);
await db.exec(`update public.cards set price_evidence='{"checkedAt":"2026-10-03T00:00:00Z","method":"manual","sourceLabel":"Manual estimate","sourceUrl":"","estimateCad":30,"sales":[]}' where id='${bulkOne}'`);
assert.equal((await db.query(`select public.bulk_update_cards(array['${bulkOne}','${bulkTwo}']::uuid[],'{"team":"Canadiens","parallel":""}','${bulkBinder}') n`)).rows[0].n,2);
const bulkRows=(await db.query(`select player,team,parallel,quantity,estimated_value_cad,price_evidence from public.cards where id=any(array['${bulkOne}','${bulkTwo}']::uuid[]) order by player`)).rows;
assert.equal(bulkRows[0].quantity,9);assert.equal(Number(bulkRows[0].estimated_value_cad),30);assert.equal(bulkRows[0].price_evidence,null);assert(bulkRows.every(row=>row.team==='Canadiens'&&row.parallel===''));
await db.query(`select public.bulk_update_cards(array['${bulkOne}','${bulkTwo}']::uuid[],'{}','${bulkBinder}')`);
assert.equal((await db.query(`select count(*)::int n from public.binder_cards where binder_id='${bulkBinder}'`)).rows[0].n,2);
await db.exec('reset role;set role anon;');await assert.rejects(db.query(`select public.bulk_update_cards(array['${bulkOne}']::uuid[],'{"brand":"X"}',null)`),/permission denied/);await db.exec('reset role;');
console.log('PASS atomic owner-only bulk changes, binder assignment, duplicate protection and pricing invalidation');

await db.exec(await readFile(new URL('../supabase/migrations/20261003035143_invalidate_changed_card_pricing.sql',import.meta.url),'utf8'));
await db.exec(`set role authenticated;select set_config('request.jwt.claim.sub','${a}',false);update public.cards set price_evidence='{"checkedAt":"2026-10-03T00:00:00Z","method":"manual","sourceLabel":"Manual estimate","sourceUrl":"","estimateCad":30,"sales":[]}' where id='${bulkOne}';update public.cards set quantity=10 where id='${bulkOne}';`);
assert.notEqual((await db.query(`select price_evidence from public.cards where id='${bulkOne}'`)).rows[0].price_evidence,null);
await db.exec(`update public.cards set set_name='Changed set' where id='${bulkOne}'`);
assert.equal((await db.query(`select price_evidence from public.cards where id='${bulkOne}'`)).rows[0].price_evidence,null);
await db.exec('reset role;');console.log('PASS identity edits clear stale pricing while quantity-only edits preserve it');

await db.exec(await readFile(new URL('../supabase/migrations/20261003123904_pricing_provider_check.sql',import.meta.url),'utf8'));
await db.exec('set role authenticated;');await assert.rejects(db.query('select * from public.pricing_provider_checks'),/permission denied/);await db.exec('reset role;set role anon;');await assert.rejects(db.query('select * from public.pricing_provider_checks'),/permission denied/);await db.exec('reset role;set role service_role;');await db.exec("insert into public.pricing_provider_checks(id) values('apify-suzuki-v1')");await assert.rejects(db.exec("insert into public.pricing_provider_checks(id) values('apify-suzuki-v1')"),/duplicate/);await db.exec('reset role;');console.log('PASS provider diagnostic reservations are service-only and cannot be duplicated');

await db.exec(await readFile(new URL('../supabase/migrations/20261003124656_automatic_sold_price_cache.sql',import.meta.url),'utf8'));
await db.exec('set role authenticated;');await assert.rejects(db.query("select public.reserve_sold_price_lookup('"+'a'.repeat(64)+"')"),/permission denied/);await assert.rejects(db.query('select * from public.sold_price_cache'),/permission denied/);await db.exec('reset role;set role service_role;');
const lookupKey='a'.repeat(64);assert.equal((await db.query(`select public.reserve_sold_price_lookup('${lookupKey}') status`)).rows[0].status,'start');assert.equal((await db.query(`select public.reserve_sold_price_lookup('${lookupKey}') status`)).rows[0].status,'pending');
await db.exec("update public.sold_price_budget set lookups=50");assert.equal((await db.query(`select public.reserve_sold_price_lookup('${'b'.repeat(64)}') status`)).rows[0].status,'budget');
await db.exec(`update public.sold_price_cache set state='SUCCEEDED',result='{}' where query_key='${lookupKey}'`);assert.equal((await db.query(`select public.reserve_sold_price_lookup('${lookupKey}') status`)).rows[0].status,'cached');
await db.exec('reset role;');console.log('PASS service-only sold lookup reservation deduplicates pending runs and enforces the monthly budget');
await db.close();
