"use client";
import {useEffect,useState} from 'react';import {supabase} from '@/lib/supabase';
import type {SoldListing} from '@/lib/apify-sold-results';
type Result={status:string;message?:string;checkedAt?:string;matchedCount?:number;fx?:{rate:number;date:string}|null;estimateCad?:number|null;items?:(SoldListing&{excludedReason:string|null})[]};
export default function AutomaticSoldPrices({cardId}:{cardId:string}){
 const [result,setResult]=useState<Result>({status:'pending'});
 useEffect(()=>{const controller=new AbortController();let timer:ReturnType<typeof setTimeout>|undefined;let attempts=0;
  async function load(){try{const {data}=await supabase!.auth.getSession();if(controller.signal.aborted)return;const response=await fetch('/api/pricing/sold?cardId='+encodeURIComponent(cardId),{headers:{Authorization:`Bearer ${data.session?.access_token||''}`},signal:controller.signal,cache:'no-store'});const json=await response.json();if(!response.ok)throw Error(json.error||'Could not load sold prices.');setResult(json);if(json.status==='pending'&&++attempts<24)timer=setTimeout(load,5000);else if(json.status==='pending')setResult({status:'pending-later',message:'The lookup is still running. Reopen this card in a moment to see the result.'});}catch{if(!controller.signal.aborted)setResult({status:'unavailable',message:'Sold prices are temporarily unavailable. You can still use manual price review.'});}}
  void load();return()=>{controller.abort();if(timer)clearTimeout(timer);};
 },[cardId]);
 return <section className="softPanel automaticSoldPrices" style={{marginTop:16,overflowWrap:'anywhere'}} aria-label="Automatic sold prices"><h3>Recent sold prices</h3>{result.status==='pending'?<p className="helperText" role="status">Looking up completed sales… Your card is ready to use while this loads.</p>:null}{result.estimateCad!=null?<p><strong>${result.estimateCad.toFixed(2)} CAD</strong> median · {result.matchedCount} matching {result.matchedCount===1?'sale':'sales'}</p>:null}{result.fx?<p className="helperText">USD converted at {result.fx.rate.toFixed(4)} CAD per USD · Bank of Canada rate dated {result.fx.date}</p>:null}{result.message?<p className="helperText">{result.message}</p>:null}{result.checkedAt?<p className="helperText">Checked {new Date(result.checkedAt).toLocaleString()} · eBay Canada via Apify · cached for 24 hours</p>:null}{result.items?.length?<details><summary>View sold listings and excluded matches</summary><ul>{result.items.map((item,index)=><li key={item.url||index} style={{margin:'12px 0'}}>{item.url?<a href={item.url} target="_blank" rel="noopener noreferrer">{item.title}</a>:item.title}<p className="helperText">{item.bestOfferAccepted?'Accepted offer amount hidden':item.amount!=null?`${item.currency} $${item.amount.toFixed(2)}`:'Price unavailable'} · {item.soldAt||'Date unavailable'}{item.excludedReason?` · Excluded: ${item.excludedReason}`:' · Included'}</p></li>)}</ul></details>:null}<p className="helperText">Automatic comparisons do not change your saved estimate. Hidden Best Offers, pick-lists and different variants are excluded. Check condition against your card.</p></section>;
}
